[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
rust_decimal = "1.36.0"
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.137"
