[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
numeric = { path = "../numeric" }

[dev-dependencies]
serde_json = "1.0.137"
