name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.84.0
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add rustfmt clippy
      - run: cargo build
      - run: cargo test
      - run: cargo fmt --check
      - run: cargo clippy
